# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "41e76936bfc811aa58c34520d6c1a4dc"
name = "Trax-API"
handle = "trax-api"
application_url = "https://trax-api.test/test"
embedded = true

[build]
dev_store_url = "traxdev.myshopify.com"

[auth]
redirect_urls = [ "https://trax-api.test/authenticate" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
